#
# Lint
#

Lint/UnusedArgument:
  Excluded:
    - "**/*.ecr"

# Exclude assigns for ECR files
Lint/UselessAssign:
  Excluded:
    - "**/*.ecr"
    - src/invidious.cr
    - src/invidious/helpers/errors.cr
    - src/invidious/routes/**/*.cr

Lint/NotNil:
  Enabled: false

Lint/SpecFilename:
  Excluded:
    - spec/parsers_helper.cr

#
# Style
#

# This requires a rewrite of most data structs (and their usage) in Invidious.
Naming/QueryBoolMethods:
  Enabled: false

Naming/BlockParameterName:
  Enabled: false

#
# Metrics
#

# Ignore function complexity (number of if/else & case/when branches)
# For some functions that can hardly be simplified for now
Metrics/CyclomaticComplexity:
  Enabled: false
