FROM postgres:10

# Do not require a PostgreSQL superuser password.
# See https://github.com/docker-library/postgres/issues/681.
ENV POSTGRES_HOST_AUTH_METHOD trust

ADD ./config/sql /config/sql
ADD ./docker/entrypoint.postgres.sh /entrypoint.sh

ENTRYPOINT [ "/entrypoint.sh" ]
CMD [ "postgres" ]
