# SPDX-FileCopyrightText: 2019 Omar Roth <omarroth@protonmail.com>
#
# SPDX-License-Identifier: AGPL-3.0-or-later

FROM postgres:10

ENV POSTGRES_USER postgres

ADD ./config/sql /config/sql
ADD ./docker/entrypoint.postgres.sh /entrypoint.sh

ENTRYPOINT [ "/entrypoint.sh" ]
CMD [ "postgres" ]
